### PR TITLE
VuePress Website for Docs

### PR DESCRIPTION
**Pull request by thunderbiscuit**
This will set up the basic structure to deploy a VuePress static website for Zap docs.

### Automatic Deployment
I am working on setting up the repo with Travis CI, but for now any maintainer of the repo can simply deploy to GitPages by running the `deploy.sh` script in the root directory.

The files will be pushed to a branch called gh-pages, and so GitPages has to be tracking that branch for the site to deploy there. The option of which branch to track for GitPages is under the _Settings_ tab of the repo.

### CODE REVIEW

**Comment by mrfelton** [comment]
Hi @thunderBiscuit .

Thanks for putting this together. I had a little play with it locally and generally speaking I like what I see. Here are a few things that would need to be done for this to be closer to something that could be considered as merge ready:

- Replace lorum ipsum test with real copy.
- "Zap Wallet Docs" => "Zap Documentation" (IMO)
- Add copy to empty placeholder pages (or remove entirely)
- Add Zap favicon
- Use our font (https://fonts.google.com/specimen/Roboto)

On an unrelated node, have you looked at [Gatsby](https://www.gatsbyjs.org/)? Reason that I ask is that by staying within the React ecosystem we give ourselves the ability to (re)use existing web components directly in the docs site. Not saying that this is something that we specifically want to do, just a consideration.

Another thing that could be interesting for you to look at is [mdxjs](https://mdxjs.com/) which again enables integration of React components directly within simple markdown documents.

Also [react-static](https://github.com/react-static/react-static).

Obviously there are many ways to skin a cat and I don't have anything against using VuePress but I know that you were doing some investigation into these different tools so wanted to get your throughs.

Just a thought.

**Comment by thunderbiscuit** [comment]
@mrfelton ok so a few thoughts on my end around this. First, favicon, fonts, title, that's super easy, I can fix immediately. Thanks for pointing them out. For the Lorem Ipsum, I just wasn't comfortable writing something for you guys, so I kept it as a placeholder to showcase what could be done with the defaults, but yes we should definitely write something official (maybe I could open an issue for that?).

Now for the choice of VuePress vs others. I am starting to learn more about static site generators and I picked VuePress as a start because its default theme is for documentation and it's got great support, but I am totally open to any other solution, particularly because I think you have to find something that fits your project and your community. If your devs are used to working with React and you think that using a React based tool can leverage that, I'm all for that. I want to work with the project on what's good for the long run.

I looked at Gatsby (undoubtedly the most popular JS static site generator). It looks great and a very big/active project. It appears that the best way to develop documentation using it is a theme called _[Docz](https://www.docz.site/)_. Have you had a look at it? I think it could be a contender if you preferred a React solution. It does implement mdxjs off the bat too, so I assume that's pretty cool, although I have not worked with it myself yet (looking into it now).

I was able to find some examples of documentation websites built with the _Docz_ theme, and I think they look pretty dope:
1. https://smooth-ui.smooth-code.com/
2. https://dfee.github.io/rbx/

So I guess after opening this PR and discussing and looking into it, I realize that there might need to be more conversation happening first around _how_ exactly to go about scaling up the project's growing documentation needs, and the potential choices ahead to achieve that. Do you have other people you'd like to get input from on this that you can invite to this thread? Or should we open an separate issue on this? I realize I'd be uncomfortable if you merged my stuff when I just arrived a few weeks ago and don't know the vibe just yet. I'm certainly not trying to push my ideas on others. If anyone else has ideas on this, I'm super interested. 

How can we build rad docs for Zap?

**Comment by thunderbiscuit** [comment]
After further consideration, we will be exploring [Gatsby](https://www.gatsbyjs.org/) and [Docz](https://www.docz.site/) for the documentation website, as they are closer to the technology stack of Zap; the wallet has components that could potentially be reused, and the greater flexibility of Gatsby is likely to come in handy because of the breath of Zap products (desktop, android, ios).

I suggest we close this PR. I'll be making a new one!

**Comment by JimmyMow** [comment]
Nice one @thunderBiscuit! Sounds good. Let me know if we can be helpful in any way.

**Comment by JimmyMow** [comment]
@thunderBiscuit any update on this? Happy to build on and help out with whatever you've started. I'd love to get a new and better docs/tutorials site up

**Comment by dennisreimann** [comment]
I could also help with that, in case @thunderBiscuit wants to tag team it. I have recently done the VuePress setup for the new [Wasabi docs](https://docs.wasabiwallet.io), which can also be used as a reference on how to do all kinds of customizations.

**Comment by thunderbiscuit** [comment]
Hello to both of you! Yep indeed much has happened since the last time I posted on here. I've been in a private chat with @mrfelton about testing Gatsby because it uses React and it's closer to the technology stack of Zap. I've learned a lot about Gatsby and am now using it for some personal project. It's extremely powerful and a worthy pursuit. It also forced me to get into React, which I did not know before; I am quite enjoying learning that right now. Anyway.

The short answer is that the best way to create docs on Gatsby is through a project called _Docz_. I have a working version [here](https://github.com/thunderBiscuit/zap-docs/tree/master). The only hiccup is that Docz just updated to v2 a few weeks back, and that's the version that is using Gatsby in the background as bundler. V2 is not ready for showtime yet in my opinion, and because all examples of Docz you can find online use v1.2 or less, it was much easier to get something off the ground using that. They do, however, have some documentation on how to migrate from 1.2 to 2.0, and so over time I think we could easily migrate.

The live version I have on GitPages is giving me grief over finding the images in the public folder, so you'll have to excuse that for now. But you can deploy locally and it works like a charm. I include some screenshots here. I am happy to forward some of the more detailed thinking behind all of the above, as I have them all a bit more fleshed out in discussions with @mrfelton.

screenshot0

screenshot1

**Comment by mrfelton** [comment]
We've opted to move forwards with the docz framework using the work from @thunderBiscuit in https://github.com/LN-Zap/zap-tutorials/pull/23 as a starting point.

I have merged this through into the `next` branch and will continue development in that branch until we are ready to merge it through to master and release.

**Pull request closed without merging**
